#pragma once

#define DATA_ARRAY_SIZE 144
#define ACTIVITY_BLOCK_MINUTES 5
#define FAST_POLL_MIN_SPM 30
#define MOVEMENT_UPDATE_MIN_SECONDS 10

#define MESSAGE_ID_WORKER_INSTANT_UPDATE 100

#define PERSIST_HEALTH_LAST_BLOCK_ACTIVITY_TIME 100
#define PERSIST_HEALTH_LAST_BLOCK_ACTIVITY_VALUE 101
#define PERSIST_HEALTH_ACTIVITY 102
#define PERSIST_HEALTH_SLEEP 103
#define PERSIST_HEALTH_ACTIVITY_GOAL_TIME 104
#define PERSIST_HEALTH_LAST_ACTIVITY_TIME 105
#define PERSIST_HEALTH_LAST_ACTIVITY_VALUE 106
#define PERSIST_HEALTH_LAST_ACTIVITY_SPM 107

#define SLEEP_NORMAL 1
#define SLEEP_RESTFUL 2

void health_update_minute();
void health_update_half_hour();
void health_init();
void health_deinit();
void health_movement_update();

void _save_current_activity();