#pragma once

#define DATA_ARRAY_SIZE 144
#define ACTIVITY_BLOCK_MINUTES 5
#define FAST_POLL_MIN_SPM 30
#define UPDATE_ACTIVITY_MS 10000

#define PERSIST_HEALTH_LAST_BLOCK_ACTIVITY_TIME 100
#define PERSIST_HEALTH_LAST_BLOCK_ACTIVITY_VALUE 101
#define PERSIST_HEALTH_ACTIVITY 102
#define PERSIST_HEALTH_SLEEP 103
#define PERSIST_HEALTH_ACTIVITY_GOAL_TIME 104
#define PERSIST_HEALTH_LAST_ACTIVITY_TIME 105
#define PERSIST_HEALTH_LAST_ACTIVITY_VALUE 106
#define PERSIST_HEALTH_LAST_ACTIVITY_SPM 107
#define PERSIST_HEALTH_FAST_POLL_ACTIVE 108

void health_get_activity(uint8_t *data);
void health_get_sleep(uint8_t *data);
